name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        id: ruff
        with:
          src: ../../password-generator-cli.py
          args: --fix --ignore=E203,E231,E266,E402,E501,E703,F821,W291,W293
      
